name: "User Story"
description: "Create a user story with clear value and acceptance criteria"
title: "[User Story]: "
labels: ["user story"]
body:
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: "Use: As a [type of user], I want [goal], so that [benefit]."
      placeholder: "As a ..., I want ..., so that ..."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: "List conditions that must be true for this to be done."
      placeholder: |
        - [ ] Given ... when ... then ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / Context
      placeholder: "Any extra details, links, screenshots, constraints..."
    validations:
      required: false
